<script>

    $(function () {

    })

</script>


<script>
    var module_box_slide_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >幻灯片</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择幻灯片:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_slide->count())",
        "                                                        @foreach($micro_page_componet_slide as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_coupon_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >优惠券</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择优惠券:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_coupon->count())",
        "                                                        @foreach($micro_page_componet_coupon as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_nav_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >快捷导航</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择快捷导航:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_nav->count())",
        "                                                        @foreach($micro_page_componet_nav as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_cube_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >魔方</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择魔方:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_cube->count())",
        "                                                        @foreach($micro_page_componet_cube as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_seckill_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >秒杀</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择秒杀:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_seckill->count())",
        "                                                        @foreach($micro_page_componet_seckill as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_free_event_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >集call</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择集call:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_free_event->count())",
        "                                                        @foreach($micro_page_componet_free_event as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_groupon_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >拼团</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择拼团:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_groupon->count())",
        "                                                        @foreach($micro_page_componet_groupon as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_suit_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >套餐</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择套餐:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_suit->count())",
        "                                                        @foreach($micro_page_componet_suit as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_category_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >分类商品</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择分类商品:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_category->count())",
        "                                                        @foreach($micro_page_componet_category as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_goods_group_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >商品分组</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\">选择商品分组:</div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    @if($micro_page_componet_goods_group->count())",
        "                                                        @foreach($micro_page_componet_goods_group as $slide_item)",
        "                                                            <option value=\"{{$slide_item->id}}\">{{$slide_item->name}}</option>",
        "                                                        @endforeach",
        "                                                    @endif",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>

<script>
    var module_box_search_html= ["<div class=\"module-box-slide\">",
        "                                <div class=\"box-ranks box-border\" data-type=\"micro_page_componet_slide\">",
        "                                    <span style=\"margin-left: 20px;\" >搜索框</span>",
        "                                    <b class=\"caret pull-right\" style=\"margin-top:25px;margin-right:15px;\"></b>",
        "                                </div>",
        "                                <div class=\"col-sm-12 module-box-son box-border box-select-hide\" style=\"border-top:0;background-color: #FFF3F3F3\">",
        "                                    <div class=\"box-select\" style=\"min-height:100px;\">",
        "                                        <div class=\"row\" style='display: none'>",
        "                                            <div class=\"col-sm-3\" style=\"text-align:right\"></div>",
        "                                            <div class=\"col-sm-9\" style=\"margin-top:15px;\">",
        "                                                <select class=\"form-control\" name=\"micro_page_type\">",
        "                                                    <option selected value=\"-1\"></option>",
        "                                                </select>",
        "                                            </div>",
        "                                        </div>",
        "                                        <div class=\"row\">",
        "                                            <div class=\"col-sm-3\" style=\"margin-left: 45px;\">",
        "                                                <a class=\"remove-module-box\" style=\"color: #ff1000\">移除</a>",
        "                                            </div>",
        "                                        </div>",
        "                                    </div>",
        "                                </div>",
        "                                <div class=\"col-sm-12\" style=\"height:8px;background-color: #FFF3F3F3\"></div>",
        "                            </div>"].join("");

</script>