<?php
/**
 * Created by PhpStorm.
 * User: eddy
 * Date: 2016/10/17
 * Time: 11:47
 */

namespace GuoJiangClub\EC\Open\Backend\Store\Facades;

use Illuminate\Support\Facades\Facade;

class GoodsService extends Facade {

    protected static function getFacadeAccessor()
    {
        return 'GoodsService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}